import org.junit.jupiter.api.Test
import java.io.File
import kotlin.test.assertEquals

class Day8Test {
    val sample = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """.trimIndent().split("\n")

    @Test
    fun testFirstSample1() {
        val transformed = Day8.transform(sample1)
        val (antinodeLocations, map) = Day8.firstTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        assertEquals(sample1WithSolution, solution)
        assertEquals(2, antinodeLocations.size)
    }

    @Test
    fun testFirstSample2() {
        val transformed = Day8.transform(sample2)
        val (antinodeLocations, map) = Day8.firstTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        assertEquals(sample2, solution)
        assertEquals(4, antinodeLocations.size)
    }

    @Test
    fun testFirstSample3() {
        val transformed = Day8.transform(sample3)
        val (antinodeLocations, map) = Day8.firstTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        assertEquals(sample3WithSolution, solution)
        assertEquals(4, antinodeLocations.size)
    }

    @Test
    fun testFirstSample() {
        val transformed = Day8.transform(sample)
        val (antinodeLocations, map) = Day8.firstTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        assertEquals(sampleWithSolution, solution)
        println(solution.joinToString("\n"))
        assertEquals(14, antinodeLocations.size)
    }

    // 250 too low
    // 286 too high
    @Test
    fun testFirstTask() {
        val taskInput = File("$path/day8.txt").readLines()
        val transformed = Day8.transform(taskInput)
        val (antinodeLocations, map) = Day8.firstTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        print("solution: " + antinodeLocations.size)
        assertEquals(265, antinodeLocations.size)
    }

    @Test
    fun testTask2Sample1() {
        val transformed = Day8.transform(sample1Task2)
        val (antinodeLocations, map) = Day8.secondTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        println("solution: " + antinodeLocations.size)
        assertEquals(sample1Task2WithSolution, solution)
        println(solution.joinToString("\n"))
        assertEquals(9, antinodeLocations.size)
    }

    @Test
    fun testSecondSample() {
        val transformed = Day8.transform(sampleTask2)
        val (antinodeLocations, map) = Day8.secondTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        assertEquals(sampleTask2WithSolution, solution)
        println(solution.joinToString("\n"))
        assertEquals(34, antinodeLocations.size)
    }

    @Test
    fun testSecondTask() {
        val taskInput = File("$path/day8.txt").readLines()
        val transformed = Day8.transform(taskInput)
        val (antinodeLocations, map) = Day8.secondTask(transformed)
        val solution: List<String> = map.map { it.joinToString("") { c -> c.toString() } }
        println("solution: " + antinodeLocations.size)
        //println(solution.joinToString("\n"))
        assertEquals(962, antinodeLocations.size)
    }

    val sampleWithSolution = """
        ......#....#
        ...#....0...
        ....#0....#.
        ..#....0....
        ....0....#..
        .#....A.....
        ...#........
        #......#....
        ........A...
        .........A..
        ..........#.
        ..........#.
    """.trimIndent().split("\n")

    val sample1 = """
        ..........
        ..........
        ..........
        ....a.....
        ..........
        .....a....
        ..........
        ..........
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample1WithSolution = """
        ..........
        ...#......
        ..........
        ....a.....
        ..........
        .....a....
        ..........
        ......#...
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample2 = """
        ..........
        ..........
        ..........
        ....a.....
        ........a.
        .....a....
        ..........
        ..........
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample2WithSolution = """
        ..........
        ...#......
        #.........
        ....a.....
        ........a.
        .....a....
        ..#.......
        ......#...
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample3= """
        ..........
        ..........
        ..........
        ....a.....
        ........a.
        .....a....
        ..........
        ......A...
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample3WithSolution = """
        ..........
        ...#......
        #.........
        ....a.....
        ........a.
        .....a....
        ..#.......
        ......A...
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample1Task2 =  """
        T.........
        ...T......
        .T........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample1Task2WithSolution =  """
        T....#....
        ...T......
        .T....#...
        .........#
        ..#.......
        ..........
        ...#......
        ..........
        ....#.....
        ..........
    """.trimIndent().split("\n")

    val sampleTask2 = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent().split("\n")

    val sampleTask2WithSolution = """
        ##....#....#
        .#.#....0...
        ..#.#0....#.
        ..##...0....
        ....0....#..
        .#...#A....#
        ...#..#.....
        #....#.#....
        ..#.....A...
        ....#....A..
        .#........#.
        ...#......##
    """.trimIndent().split("\n")

}