import org.junit.jupiter.api.Test
import java.io.File
import kotlin.test.assertEquals

class Day8Test {
    val sample = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """.trimIndent().split("\n")


    @Test
    fun testFirstSample() {
        val transformed = Day8.transform(sample)
        val (antinodeLocations, map) = Day8.firstTask(transformed)
        val solution: List<String> = map.map { it.joinToString { c -> c.toString() } }
        assertEquals(sampleWithSolution, solution)
        assertEquals(14, antinodeLocations.size)
    }

    @Test
    fun testFirstTask() {
        val taskInput = File("$path/day8.txt").readLines()
    }


    @Test
    fun testSecondSample() {
    }

    @Test
    fun testSecondTask() {
        val taskInput = File("$path/day8.txt").readLines()
    }

    val sampleWithSolution = """
        ......#....#
        ...#....0...
        ....#0....#.
        ..#....0....
        ....0....#..
        .#....A.....
        ...#........
        #......#....
        ........A...
        .........A..
        ..........#.
        ..........#.
    """.trimIndent().split("\n")

    val sample1 = """
        ..........
        ...#......
        ..........
        ....a.....
        ..........
        .....a....
        ..........
        ......#...
        ..........
        ..........
    """.trimIndent().split("\n")

    val sample2 = """
        ..........
        ...#......
        #.........
        ....a.....
        ........a.
        .....a....
        ..#.......
        ......#...
        ..........
        ..........
    """.trimIndent().split("\n")


    val sample3 = """
        ..........
        ...#......
        #.........
        ....a.....
        ........a.
        .....a....
        ..#.......
        ......A...
        ..........
        ..........
    """.trimIndent().split("\n")
}